### ISSUE TITLE
Duplicated setting of UCX_MEMTYPE_CACHE variable

### ISSUE THREAD

**Issue by sjsprecious** [sherimickelson/CM1_benchmarkingWF#4]
The `UCX_MEMTYPE_CACHE` variable is set twice in the job submission script.

https://github.com/sherimickelson/CM1_benchmarkingWF/blob/40d209b8b4eb9b63fb5c363a6b0a9e8e99fb585e/create_runscript.py#L30

**Comment by sherimickelson** [comment]
@sjsprecious , thanks for catching this.  I just pushed the changes into #8b22ffc within the main branch.
